import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";
import Script from "next/script";
import { KAKAO_JS_KEY } from "./constants";
declare global {
	interface Window {
		kakao: any;
		closeOverlay: any;
	}
}
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Script
					strategy={"beforeInteractive"}
					src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${KAKAO_JS_KEY}&autoload=false&libraries=services,clusterer,drawing`}
				/>
				<Navigation />
				{children}
			</body>
		</html>
	);
}
